# Generated by Django 5.2.4 on 2025-07-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_view_userprofile', 'Can view user profile'), ('can_create_userprofile', 'Can create user profile'), ('can_edit_userprofile', 'Can edit user profile'), ('can_delete_userprofile', 'Can delete user profile')]},
        ),
    ]
